# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import music_recommendation_pb2 as music__recommendation__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in music_recommendation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MusicRecommendationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRecommendation = channel.unary_unary(
                '/MusicRecommendationService/CreateRecommendation',
                request_serializer=music__recommendation__pb2.CreateRecommendationRequest.SerializeToString,
                response_deserializer=music__recommendation__pb2.CreateRecommendationResponse.FromString,
                _registered_method=True)
        self.GetRecommendation = channel.unary_unary(
                '/MusicRecommendationService/GetRecommendation',
                request_serializer=music__recommendation__pb2.GetRecommendationRequest.SerializeToString,
                response_deserializer=music__recommendation__pb2.GetRecommendationResponse.FromString,
                _registered_method=True)
        self.UpdateRecommendation = channel.unary_unary(
                '/MusicRecommendationService/UpdateRecommendation',
                request_serializer=music__recommendation__pb2.UpdateRecommendationRequest.SerializeToString,
                response_deserializer=music__recommendation__pb2.UpdateRecommendationResponse.FromString,
                _registered_method=True)
        self.DeleteRecommendation = channel.unary_unary(
                '/MusicRecommendationService/DeleteRecommendation',
                request_serializer=music__recommendation__pb2.DeleteRecommendationRequest.SerializeToString,
                response_deserializer=music__recommendation__pb2.DeleteRecommendationResponse.FromString,
                _registered_method=True)


class MusicRecommendationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRecommendation(self, request, context):
        """Create a new music recommendation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendation(self, request, context):
        """Get a recommendation by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRecommendation(self, request, context):
        """Update an existing recommendation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRecommendation(self, request, context):
        """Delete a recommendation by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicRecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRecommendation,
                    request_deserializer=music__recommendation__pb2.CreateRecommendationRequest.FromString,
                    response_serializer=music__recommendation__pb2.CreateRecommendationResponse.SerializeToString,
            ),
            'GetRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendation,
                    request_deserializer=music__recommendation__pb2.GetRecommendationRequest.FromString,
                    response_serializer=music__recommendation__pb2.GetRecommendationResponse.SerializeToString,
            ),
            'UpdateRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRecommendation,
                    request_deserializer=music__recommendation__pb2.UpdateRecommendationRequest.FromString,
                    response_serializer=music__recommendation__pb2.UpdateRecommendationResponse.SerializeToString,
            ),
            'DeleteRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRecommendation,
                    request_deserializer=music__recommendation__pb2.DeleteRecommendationRequest.FromString,
                    response_serializer=music__recommendation__pb2.DeleteRecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MusicRecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MusicRecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MusicRecommendationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MusicRecommendationService/CreateRecommendation',
            music__recommendation__pb2.CreateRecommendationRequest.SerializeToString,
            music__recommendation__pb2.CreateRecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MusicRecommendationService/GetRecommendation',
            music__recommendation__pb2.GetRecommendationRequest.SerializeToString,
            music__recommendation__pb2.GetRecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MusicRecommendationService/UpdateRecommendation',
            music__recommendation__pb2.UpdateRecommendationRequest.SerializeToString,
            music__recommendation__pb2.UpdateRecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MusicRecommendationService/DeleteRecommendation',
            music__recommendation__pb2.DeleteRecommendationRequest.SerializeToString,
            music__recommendation__pb2.DeleteRecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
