# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: music_recommendation.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'music_recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amusic_recommendation.proto\"K\n\x1b\x43reateRecommendationRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x02 \x01(\t\x12\r\n\x05genre\x18\x03 \x01(\t\";\n\x1c\x43reateRecommendationResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x18GetRecommendationRequest\x12\n\n\x02id\x18\x01 \x01(\t\"U\n\x19GetRecommendationResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\r\n\x05genre\x18\x04 \x01(\t\"W\n\x1bUpdateRecommendationRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\r\n\x05genre\x18\x04 \x01(\t\"/\n\x1cUpdateRecommendationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\x1b\x44\x65leteRecommendationRequest\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x1c\x44\x65leteRecommendationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe7\x02\n\x1aMusicRecommendationService\x12S\n\x14\x43reateRecommendation\x12\x1c.CreateRecommendationRequest\x1a\x1d.CreateRecommendationResponse\x12J\n\x11GetRecommendation\x12\x19.GetRecommendationRequest\x1a\x1a.GetRecommendationResponse\x12S\n\x14UpdateRecommendation\x12\x1c.UpdateRecommendationRequest\x1a\x1d.UpdateRecommendationResponse\x12S\n\x14\x44\x65leteRecommendation\x12\x1c.DeleteRecommendationRequest\x1a\x1d.DeleteRecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATERECOMMENDATIONREQUEST']._serialized_start=30
  _globals['_CREATERECOMMENDATIONREQUEST']._serialized_end=105
  _globals['_CREATERECOMMENDATIONRESPONSE']._serialized_start=107
  _globals['_CREATERECOMMENDATIONRESPONSE']._serialized_end=166
  _globals['_GETRECOMMENDATIONREQUEST']._serialized_start=168
  _globals['_GETRECOMMENDATIONREQUEST']._serialized_end=206
  _globals['_GETRECOMMENDATIONRESPONSE']._serialized_start=208
  _globals['_GETRECOMMENDATIONRESPONSE']._serialized_end=293
  _globals['_UPDATERECOMMENDATIONREQUEST']._serialized_start=295
  _globals['_UPDATERECOMMENDATIONREQUEST']._serialized_end=382
  _globals['_UPDATERECOMMENDATIONRESPONSE']._serialized_start=384
  _globals['_UPDATERECOMMENDATIONRESPONSE']._serialized_end=431
  _globals['_DELETERECOMMENDATIONREQUEST']._serialized_start=433
  _globals['_DELETERECOMMENDATIONREQUEST']._serialized_end=474
  _globals['_DELETERECOMMENDATIONRESPONSE']._serialized_start=476
  _globals['_DELETERECOMMENDATIONRESPONSE']._serialized_end=523
  _globals['_MUSICRECOMMENDATIONSERVICE']._serialized_start=526
  _globals['_MUSICRECOMMENDATIONSERVICE']._serialized_end=885
# @@protoc_insertion_point(module_scope)
